//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dug
    {
        public int id_duga { get; set; }
        public string ime_prezime { get; set; }
        public string broj_telefona { get; set; }
        public System.DateTime datum_izdavanja { get; set; }
        public Nullable<System.DateTime> datum_vracanja { get; set; }
        public Nullable<int> sifra_artikla { get; set; }
        public string artikal { get; set; }
        public decimal cena { get; set; }
        public Nullable<int> knjizeno { get; set; }
    }
}
