//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racuni_knjizeno
    {
        public int id_racuna { get; set; }
        public string artikli { get; set; }
        public System.DateTime datum_izdavanja { get; set; }
        public decimal iznos { get; set; }
        public Nullable<decimal> iznos_nabavna { get; set; }
    }
}
