//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racuni_hover_mob
    {
        public int id_racuna { get; set; }
        public string prodavac { get; set; }
        public string datum_izdavanja { get; set; }
        public string artikal { get; set; }
        public decimal iznos { get; set; }
        public decimal iznos_nabavna { get; set; }
        public Nullable<int> knjizeno { get; set; }
    }
}
