//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int id_rezervacija { get; set; }
        public int sifra_artikla { get; set; }
        public int knjizeno { get; set; }
        public string ime_prezime { get; set; }
        public string broj_telefona { get; set; }
        public string artikal { get; set; }
        public decimal cena { get; set; }
        public int kolicina { get; set; }
    }
}
