//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servi
    {
        public int id_servisa { get; set; }
        public string serviser { get; set; }
        public System.DateTime datum_preuzimanja { get; set; }
        public string ime_prezime { get; set; }
        public string broj_telefona { get; set; }
        public string opis_kvara { get; set; }
        public Nullable<decimal> cena_popravke { get; set; }
        public Nullable<decimal> cena_naplate { get; set; }
    }
}
